### ISSUE TITLE
Home Portal Bar

### ISSUE THREAD

**Issue by TheLastGapple** [GappleCraftNetwork/GappleCraft-Bug-Tracker#5]
These options need to be added to the home portal bar: Store, and Apply For Staff.
play.gapplecraft.net needs to be moved all the way to the end

**Comment by arsenalfcgunners** [comment]
play.gapplecraft.net has been moved to the end.  The rest are still unresolved.

**Comment by TheHtaccess** [comment]
Features have been added.

**Comment by arsenalfcgunners** [comment]
Closing this as it has been fixed.
