### ISSUE TITLE
Website Forum Categories

### ISSUE THREAD

**Issue by TheLastGapple** [GappleCraftNetwork/GappleCraft-Bug-Tracker#6]
These forum categories need to be added:  Features and Suggestions, Mod Applications, Ban Appeals, FAQ, Off Topic, VIP Application

**Comment by arsenalfcgunners** [comment]
The suggestions one has been added.

**Comment by arsenalfcgunners** [comment]
The Mod Applications one has been added.

**Comment by arsenalfcgunners** [comment]
All categories have been added.
